# These are supported funding model platforms

github: brohvis
patreon: # Replace with a single Patreon username
open_collective: # Replace with a single Open Collective username
ko_fi: brohvis
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: # Replace with a single Liberapay username
issuehunt: # Replace with a single IssueHunt username
lfx_crowdfunding: # Replace with a single LFX Crowdfunding project-name e.g., cloud-foundry
polar: # Replace with a single Polar username
buy_me_a_coffee: brohvis
custom: ['shop.crtv.to', 'crtv.to']
